# Generated by Django 3.2.10 on 2022-01-28 09:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('video', models.CharField(max_length=700)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, unique=True)),
                ('lecture', models.ManyToManyField(related_name='lecture_name', to='educator.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=700)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(default='This Series is about ....')),
                ('icon', models.CharField(max_length=700)),
                ('lectures', models.IntegerField(default=0)),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educator_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('questions', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_educator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('marks', models.IntegerField(default=4)),
                ('option1', models.CharField(max_length=300)),
                ('option2', models.CharField(max_length=300)),
                ('option3', models.CharField(blank=True, max_length=300, null=True)),
                ('option4', models.CharField(blank=True, max_length=300, null=True)),
                ('answer', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='educator.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_name', to='educator.series'),
        ),
        migrations.CreateModel(
            name='EducatorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('mobile', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('gender', models.CharField(max_length=20)),
                ('birth', models.DateField(default='2004-01-01')),
                ('picture', models.CharField(max_length=700)),
                ('qual', models.TextField(null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('sample_video', models.CharField(blank=True, max_length=700, null=True)),
                ('attachment', models.CharField(blank=True, max_length=700, null=True)),
                ('educator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
