# Generated by Django 3.2.10 on 2022-01-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=90),
        ),
    ]
