# Generated by Django 3.2.4 on 2022-05-11 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educator', '0002_quiz_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('doc', models.URLField(max_length=700)),
                ('category', models.CharField(max_length=255)),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_educator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
