# Generated by Django 3.2.4 on 2022-06-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0005_remove_attachements_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachements',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_series', to='educator.series'),
        ),
    ]
