# Generated by Django 3.2.4 on 2022-06-02 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0006_attachements_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachements',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_series', to='educator.series'),
            preserve_default=False,
        ),
    ]
